name: 'Submit to Canvas'
description: 'Reads commit trailers and, when invoked, renders a PDF from a README to submit to Canvas'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  canvas_base_url:
    description: 'Base URL of your Canvas installation, without any trailing slashes'
    required: true
  canvas_token:
    description: 'canvas token'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        curl 'https://raw.githubusercontent.com/chlohal/gh-canvas/master/render-and-upload.sh' | bash
      shell: bash
      env:
          CANVAS_TOKEN: ${{ inputs.canvas_token }}
          CANVAS_BASE_URL: ${{ inputs.canvas_base_url }}
          GITHUB_TOKEN: ${{ inputs.github_token }}
